### ISSUE TITLE
Tapo P100 power outage

### ISSUE THREAD

**Issue by maxeq** [apatsufas/homebridge-tapo-p100#10]
I have a problem, I really like Tapo  P100 and want to change my starting status.

My problem is that after a power outage, the p100 does not remember theprevious state and is always turned off.

How do I changeit ?  Is there any setting for a power outage?

**Comment by apatsufas** [comment]
Hello @maxeq.
No I don't think there is such an option for the P100. This option exists on the L530 Bulb but seems to be unavailable for the P100.

**Comment by apatsufas** [comment]
TP-Link has added this option for Th P100 plugs in one of their latest firmware updates. You can configure the behavior in the Tapo app.
