### ISSUE TITLE
P100 Plug device name doesn't appear on HomeKit set up

### ISSUE THREAD

**Issue by mkilivan** [apatsufas/homebridge-tapo-p100#18]
**Describe The Bug:**

Tapo `Plug` type device name does not appear on the Home app when setting it up the first time. Instead, the IP address of the device appears. I have other devices on different platforms and their name appears normal on set-up. 

**To Reproduce:**

1. Open the Home app on an iOS device
2. Tap `+` and then `Add Accessory`
3. Follow the instructions

**Expected behavior:**

When setting up an accessory the device name should appear. Not the IP address of the device.
**Logs:**

```
[11/21/2021, 12:53:04 PM] [Tapo Smart Platform] Loading accessory from cache: 192.168.1.120
[11/21/2021, 12:53:05 PM] [Tapo Smart Platform] Restoring existing accessory from cache: 192.168.1.120
```

**Plugin Config:**

```json
{
    "name": "Tapo Smart Platform",
    "username": "__user_name__",
    "password": "___password___",
    "devices": [
        {
            "name": "Corner Light",
            "host": "192.168.1.120",
            "type": "Plug"
        }
    ],
    "platform": "TapoP100"
}
```

**Screenshots:**

<img src="https://user-images.githubusercontent.com/514813/142763172-994cb2e1-a319-4fb9-8d43-69acfcb284ec.png" width="300" height="300">

**Environment:**

* **Plugin Version**: homebridge-tapo v1.4.11
* **Homebridge Version**:  1.3.6
* **Node.js Version**:  v14.17.1
* **NPM Version**:   6.14.13
* **Operating System**:  Debian Yocto

**Comment by apatsufas** [comment]
Should be fixed with v.1.4.12

**Comment by mkilivan** [comment]
Thank you for the quick fix.
