### ISSUE TITLE
Unplugged Plug is still „available” in the home app

### ISSUE THREAD

**Issue by rob1037** [apatsufas/homebridge-tapo-p100#21]
**Describe The Bug:**
If I unplug the Plug it is still reachable in the home app and appears as offline, it’s even possible to turn it on without any failures in the home app while the plug is still unplugged

The homebridge plug-in knows that the plug is offline see logs down below

**To Reproduce:**
Install any P100 Plug and unplug it, it still appears normal in the home app and not as unreachable

**Expected behavior:**
If a plug gets unplugged it should get the status “No Response”

**Logs:**

[12.12.2021, 12:23:50] [Tapo Smart Platform] 111 Error: connect EHOSTUNREACH 192.168.xx.xx:80
[12.12.2021, 12:23:50] [Tapo Smart Platform] Get Device Info failed

**Plugin Config:**

"platforms": [
{
 "name": "Tapo Smart Platform",
 "username": "tapoaccount",
 "password": "*password",
  "devices": [
                {
                    "name": "tapo 1",
                    "host": "192.168.xx.xx",
                    "type": "Plug"
                },          
            ],
            "platform": "TapoP100"
        }
        ]

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.4.12
* **Homebridge Version**: 1.3.5 (had different problems with another plug-in at 1.3.8)
* **Node.js Version**: 16.13.0
* **NPM Version**: 8.1.0
* **Operating System**: Raspbian

**Comment by apatsufas** [comment]
Should be fixed with 1.4.14
