### ISSUE TITLE
Support for Tapo L630

### ISSUE THREAD

**Issue by veniplex** [apatsufas/homebridge-tapo-p100#40]
Is there any hope to support [Tapo L630](https://www.tapo.com/en/product/smart-light-bulb/tapo-l630/) any time soon? It looks like it is nearly the same as [L530E](https://www.tapo.com/en/product/smart-light-bulb/tapo-l530e/). I would add this model by my own if I understand the code - but I would need a lot of time to get into it. So is there maybe a fast way to add support for this model?

Thank you by the way for this great plugin! I appreciate it.

**Comment by apatsufas** [comment]
Hello @veniplex. Have you tried setting it up as an L530? If the use the same API, which they probably do, it should work.

**Comment by veniplex** [comment]
Ok @apatsufas I did set it up now as:
1. 'Light' -> It recognizes the manufacturer "TP-Link", model "Tapo L530E", firmware "1.4.17" and as serial number "Default-SerialNumber".
2. 'Colorlight' -> It recognizes the manufacturer "TP-Link", model "Tapo L530", firmware "1.4.17" and as serial number "Default-SerialNumber".
3. Interestingly I can also see a "ghost Tapo device" which is there since the last few updates. It was a pug before I renamed it. Bit it doesn't disappear...

I did also recognize that I have to restart homebridge sometimes several times until the login to Tapo is working.

Any ideas?

**Comment by apatsufas** [comment]
@veniplex about 3 you should remove cached accessories from the Homebridge settings. This should remove the ghost device. 
Regarding the login, I really don't know. Maybe a network issue? I have currently an 530 bulb and 2 P100 plugs and an P110 plug which all work without any mayor issue.

**Comment by veniplex** [comment]
@apatsufas I removed cached accessories but it still does not work. Can we add support for it? I would like to help but I need a starting point. Until now I never prorgammed anything for homebridge.

**Comment by apatsufas** [comment]
@veniplex if it doesn't even turn on or off then it is probably using a very different api as the L530.
If I find some time I will look around if any Home Assistant plug-in has support for this particular bulb and also check the Android Tapo app apk to see if I can find something there.
