### ISSUE TITLE
command?

### ISSUE THREAD

**Issue by sudoWalker** [apatsufas/homebridge-tapo-p100#44]
**Describe Your Problem:**
Is it possible to trigger my tapo p110 with a curl command?
Switching on/off in the homebridge UI is working.
**Logs:**

```

```

**Plugin Config:**

```json
{
    "name": "Tapo P110",
    "username": "walkerwhite@outlook.de",
    "password": "Passw0rd",
    "devices": [
        {
            "name": "TapoP110",
            "host": "192.168.178.42",
            "type": "Plug",
            "updateInterval": 30,
            "timeout": 2
        }
    ],
    "platform": "TapoP100"
}
```

**Screenshots:**

**Environment:**
Homebridge-IP=
http://192.168.178.100:8581/
no docker

* **Plugin Version**: homebridge-tapo v1.4.17
* **Homebridge Version**: v1.6.1
* **Node.js Version**: v16.20.1
* **NPM Version**: 9.8.1
* **Operating System**: Debian GNU/Linux 11 (bullseye)

**Comment by apatsufas** [comment]
@dukeluke not with an simple curl command. You would need to authenticate first in order to create the key pair needed for encrypting the request payload before using curl to talk to the REST API.
