### ISSUE TITLE
 Error in homebridge logs

### ISSUE THREAD

**Issue by PencilDH** [apatsufas/homebridge-tapo-p100#9]
Hi first off all awesome plug-in thanks

I had this error come up on my tapo p100 plug (firmware 1.4.5) it seem to work but just wanted to let you know
![705476EB-B29C-4F5D-9FA5-6FE1FBCE3140](https://user-images.githubusercontent.com/19908009/122451612-44262680-cfa0-11eb-86c6-4566768fe914.jpeg)

**Comment by apatsufas** [comment]
Hello @PencilDHz. From my experience this kind of error messages appear when the plug-in isn't able, for some reason, to communicate with the device. I hadn't had any time lately to look further into this, but I'll do as soon as I find some time.

**Comment by cheetah3k5** [comment]
I have the exact error. The plugin still works, but after a few minutes after a restart, it stops getting the plugins’ status. A few clicks on the toggles seems to get it communicating again (only with the device that i switched on and off. Couldn’t find anything about this anywhere except this post. Weird

**Comment by apatsufas** [comment]
In the latest versions of the plugin, if this error is encountered the plugin will retry to connect to the Tapo device.
